displayName=Toggle Buttons
author=Y0RI0
description=Runelite plugin for creating clickable buttons that toggle other plugins
tags=button,buttons,toggle,click,peek,hide,unhide
plugins=com.togglebuttons.ToggleButtonsPlugin
build=standard
