displayName=Toggle Buttons
author=Y0RI0
description=Runelite plugin for creating clickable buttons that toggle other plugins
tags=
version=
plugins=com.togglebuttons.ToggleButtonsPlugin
build=standard
