package com.togglebuttons;

/*
* Manages button icon images. When the user picks a file it is
* copied into .runelite/toggle-buttons/ and only ever read back
* from there, per hub file IO guidelines. A file image always
* takes priority over a searched item icon.
*/

import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import lombok.extern.slf4j.Slf4j;
import net.runelite.client.RuneLite;

@Slf4j
final class ToggleButtonsImageLoader
{
	static final File IMAGE_DIR = new File(RuneLite.RUNELITE_DIR, "toggle-buttons");

	// Icons are drawn at button size; larger images are scaled down on import
	private static final int MAX_DIMENSION = 512;

	private ToggleButtonsImageLoader()
	{
	}

	// Imports a user-chosen image into the plugin directory and returns the
	// stored file's name for persistence, or null if the file is not a
	// readable image. Oversized images are scaled down rather than rejected.
	static String store(String buttonId, File chosen)
	{
		BufferedImage image = read(chosen);
		if (image == null)
		{
			return null;
		}

		if (image.getWidth() > MAX_DIMENSION || image.getHeight() > MAX_DIMENSION)
		{
			log.debug("Downscaling button image {} ({}x{}) to fit {}x{}",
				chosen, image.getWidth(), image.getHeight(), MAX_DIMENSION, MAX_DIMENSION);
			image = downscale(image);
		}

		if (!IMAGE_DIR.exists() && !IMAGE_DIR.mkdirs())
		{
			log.warn("Failed to create image directory {}", IMAGE_DIR);
			return null;
		}

		// One image per button; always stored as png since we re-encode
		final File destination = new File(IMAGE_DIR, buttonId + ".png");
		try
		{
			ImageIO.write(image, "png", destination);
			return destination.getName();
		}
		catch (IOException ex)
		{
			log.warn("Failed to write button image to {}", destination, ex);
			return null;
		}
	}

	// Scales an image down to fit MAX_DIMENSION, preserving aspect ratio
	private static BufferedImage downscale(BufferedImage image)
	{
		final double scale = (double) MAX_DIMENSION / Math.max(image.getWidth(), image.getHeight());
		final int width = Math.max(1, (int) (image.getWidth() * scale));
		final int height = Math.max(1, (int) (image.getHeight() * scale));

		final BufferedImage scaled = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
		final Graphics2D g = scaled.createGraphics();
		g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
		g.drawImage(image, 0, 0, width, height, null);
		g.dispose();
		return scaled;
	}

	// Loads a stored image by the file name persisted in the button config;
	// returns null when unset, missing, or unreadable
	static BufferedImage load(String storedName)
	{
		if (storedName == null || storedName.isEmpty())
		{
			return null;
		}

		// Stored names are generated by store(); reject anything path-like
		final File file = new File(IMAGE_DIR, new File(storedName).getName());
		if (!file.isFile())
		{
			log.debug("Button icon image not found: {}", file);
			return null;
		}
		return read(file);
	}

	// Deletes a stored image when its button no longer uses it
	static void delete(String storedName)
	{
		if (storedName == null || storedName.isEmpty())
		{
			return;
		}

		final File file = new File(IMAGE_DIR, new File(storedName).getName());
		if (file.isFile() && !file.delete())
		{
			log.debug("Failed to delete button image {}", file);
		}
	}

	private static BufferedImage read(File file)
	{
		if (!file.isFile())
		{
			return null;
		}

		try
		{
			final BufferedImage image = ImageIO.read(file);
			if (image == null)
			{
				log.warn("File is not a readable image: {}", file);
			}
			return image;
		}
		catch (IOException ex)
		{
			log.warn("Failed to read button icon image: {}", file, ex);
			return null;
		}
	}
}
