package com.togglebuttons;

/*
* Manages button icon images. When the user picks a file it is
* copied into .runelite/toggle-buttons/ and only ever read back
* from there, per hub file IO guidelines. A file image always
* takes priority over a searched item icon.
*/

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.imageio.ImageIO;
import lombok.extern.slf4j.Slf4j;
import net.runelite.client.RuneLite;

@Slf4j
final class ToggleButtonsImageLoader
{
	static final File IMAGE_DIR = new File(RuneLite.RUNELITE_DIR, "toggle-buttons");

	// Icons are drawn at button size; refuse anything unreasonably large
	private static final int MAX_DIMENSION = 512;

	private ToggleButtonsImageLoader()
	{
	}

	// Copies a user-chosen image into the plugin directory and returns the
	// stored file's name for persistence, or null if the image was rejected
	static String store(String buttonId, File chosen)
	{
		final BufferedImage image = read(chosen);
		if (image == null)
		{
			return null;
		}

		if (image.getWidth() > MAX_DIMENSION || image.getHeight() > MAX_DIMENSION)
		{
			log.warn("Rejecting button image {} ({}x{}); maximum is {}x{}",
				chosen, image.getWidth(), image.getHeight(), MAX_DIMENSION, MAX_DIMENSION);
			return null;
		}

		if (!IMAGE_DIR.exists() && !IMAGE_DIR.mkdirs())
		{
			log.warn("Failed to create image directory {}", IMAGE_DIR);
			return null;
		}

		// One image per button; the extension is preserved for ImageIO
		final String extension = extensionOf(chosen.getName());
		final File destination = new File(IMAGE_DIR, buttonId + extension);
		try
		{
			Files.copy(chosen.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
			return destination.getName();
		}
		catch (IOException ex)
		{
			log.warn("Failed to copy button image to {}", destination, ex);
			return null;
		}
	}

	// Loads a stored image by the file name persisted in the button config;
	// returns null when unset, missing, or unreadable
	static BufferedImage load(String storedName)
	{
		if (storedName == null || storedName.isEmpty())
		{
			return null;
		}

		// Stored names are generated by store(); reject anything path-like
		final File file = new File(IMAGE_DIR, new File(storedName).getName());
		if (!file.isFile())
		{
			log.debug("Button icon image not found: {}", file);
			return null;
		}
		return read(file);
	}

	// Deletes a stored image when its button no longer uses it
	static void delete(String storedName)
	{
		if (storedName == null || storedName.isEmpty())
		{
			return;
		}

		final File file = new File(IMAGE_DIR, new File(storedName).getName());
		if (file.isFile() && !file.delete())
		{
			log.debug("Failed to delete button image {}", file);
		}
	}

	private static BufferedImage read(File file)
	{
		if (!file.isFile())
		{
			return null;
		}

		try
		{
			final BufferedImage image = ImageIO.read(file);
			if (image == null)
			{
				log.warn("File is not a readable image: {}", file);
			}
			return image;
		}
		catch (IOException ex)
		{
			log.warn("Failed to read button icon image: {}", file, ex);
			return null;
		}
	}

	private static String extensionOf(String name)
	{
		final int dot = name.lastIndexOf('.');
		return dot >= 0 ? name.substring(dot) : ".png";
	}
}
